"""connection and file transfer logs

Revision ID: 133f21b95239
Revises: 1744421d83e7
Create Date: 2026-09-20 11:19:30.771592
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '133f21b95239'
down_revision: Union[str, None] = '1744421d83e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('rustdesk_id', sa.String(length=64), nullable=False),
    sa.Column('conn_id', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('from_ip', sa.String(length=64), nullable=True),
    sa.Column('peer_id', sa.String(length=64), nullable=True),
    sa.Column('peer_name', sa.String(length=255), nullable=True),
    sa.Column('conn_type', sa.Integer(), nullable=True),
    sa.Column('primary_auth', sa.Integer(), nullable=True),
    sa.Column('two_factor', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nonce', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_connection_logs_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_logs')),
    sa.UniqueConstraint('nonce', name=op.f('uq_connection_logs_nonce'))
    )
    with op.batch_alter_table('connection_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_connection_logs_rustdesk_conn', ['rustdesk_id', 'conn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connection_logs_rustdesk_id'), ['rustdesk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connection_logs_started_at'), ['started_at'], unique=False)

    op.create_table('file_transfer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('rustdesk_id', sa.String(length=64), nullable=False),
    sa.Column('conn_id', sa.String(length=32), nullable=True),
    sa.Column('peer_id', sa.String(length=64), nullable=True),
    sa.Column('peer_name', sa.String(length=255), nullable=True),
    sa.Column('from_ip', sa.String(length=64), nullable=True),
    sa.Column('audit_type', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('is_file', sa.Boolean(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_file_transfer_logs_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_transfer_logs')),
    sa.UniqueConstraint('nonce', name=op.f('uq_file_transfer_logs_nonce'))
    )
    with op.batch_alter_table('file_transfer_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_transfer_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_transfer_logs_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_transfer_logs_rustdesk_id'), ['rustdesk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_transfer_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_transfer_logs_rustdesk_id'))
        batch_op.drop_index(batch_op.f('ix_file_transfer_logs_logged_at'))
        batch_op.drop_index(batch_op.f('ix_file_transfer_logs_device_id'))

    op.drop_table('file_transfer_logs')
    with op.batch_alter_table('connection_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_logs_started_at'))
        batch_op.drop_index(batch_op.f('ix_connection_logs_rustdesk_id'))
        batch_op.drop_index('ix_connection_logs_rustdesk_conn')
        batch_op.drop_index(batch_op.f('ix_connection_logs_device_id'))

    op.drop_table('connection_logs')
    # ### end Alembic commands ###
