"""device cpu memory

Revision ID: 1744421d83e7
Revises: f8f7abb28559
Create Date: 2026-09-18 18:40:04.091410
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1744421d83e7'
down_revision: Union[str, None] = 'f8f7abb28559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('memory', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('memory')
        batch_op.drop_column('cpu')

    # ### end Alembic commands ###
