"""oidc identities and requests

Revision ID: b8d3e5f7a9c2
Revises: a9c4b7e2d6f1
Create Date: 2026-09-21 10:00:25.019910
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8d3e5f7a9c2'
down_revision: Union[str, None] = 'a9c4b7e2d6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oidc_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oidc_identities')),
    sa.UniqueConstraint('issuer', 'subject', name=op.f('uq_oidc_identities_issuer')),
    sa.UniqueConstraint('user_id', 'issuer', name=op.f('uq_oidc_identities_user_id'))
    )
    op.create_table('oidc_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('handle_hash', sa.String(length=64), nullable=True),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('binding_hash', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('device_uuid', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oidc_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oidc_requests'))
    )
    with op.batch_alter_table('oidc_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oidc_requests_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oidc_requests_handle_hash'), ['handle_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_oidc_requests_state_hash'), ['state_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_oidc_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oidc_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oidc_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_oidc_requests_state_hash'))
        batch_op.drop_index(batch_op.f('ix_oidc_requests_handle_hash'))
        batch_op.drop_index(batch_op.f('ix_oidc_requests_expires_at'))

    op.drop_table('oidc_requests')
    op.drop_table('oidc_identities')
    # ### end Alembic commands ###
