"""groups tags shares

Revision ID: c1a346230d0a
Revises: 31d1881265d3
Create Date: 2026-09-18 11:36:04.568506
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1a346230d0a'
down_revision: Union[str, None] = '31d1881265d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_groups_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('owner_id', 'name', name='uq_groups_owner_name')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_owner_id'), ['owner_id'], unique=False)

    op.create_table('device_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_shares_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_device_shares_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], name=op.f('fk_device_shares_shared_with_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_shares')),
    sa.UniqueConstraint('device_id', 'shared_with_user_id', name='uq_device_share_target')
    )
    with op.batch_alter_table('device_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_shares_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_shares_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_shares_shared_with_user_id'), ['shared_with_user_id'], unique=False)

    op.create_table('device_tags',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_tags_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_device_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'tag_id', name=op.f('pk_device_tags'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_devices_group_id_groups'), 'groups', ['group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_devices_group_id_groups'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_devices_group_id'))
        batch_op.drop_column('group_id')

    op.drop_table('device_tags')
    with op.batch_alter_table('device_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_shares_shared_with_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_shares_owner_id'))
        batch_op.drop_index(batch_op.f('ix_device_shares_device_id'))

    op.drop_table('device_shares')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_owner_id'))
        batch_op.drop_index(batch_op.f('ix_groups_name'))

    op.drop_table('groups')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    # ### end Alembic commands ###
