"""strategies connections two factor

Revision ID: d5a1c7e9b3f4
Revises: c4d8f1a2e6b3
Create Date: 2026-09-20 20:22:20.693388
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5a1c7e9b3f4'
down_revision: Union[str, None] = 'c4d8f1a2e6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('config_options', sa.Text(), nullable=False),
    sa.Column('modified_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_name'), ['name'], unique=True)

    op.create_table('login_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_challenges'))
    )
    with op.batch_alter_table('login_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_challenges_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_challenges_secret_hash'), ['secret_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_challenges_user_id'), ['user_id'], unique=False)

    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_codes'))
    )
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_codes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('live_connections', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pending_disconnect', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strategy_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_devices_strategy_id_strategies'), 'strategies', ['strategy_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_groups_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_groups_strategy_id_strategies'), 'strategies', ['strategy_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret_enc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('totp_last_step', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_column('label')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_last_step')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret_enc')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_groups_strategy_id_strategies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_groups_strategy_id'))
        batch_op.drop_column('strategy_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_devices_strategy_id_strategies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_devices_strategy_id'))
        batch_op.drop_column('strategy_id')
        batch_op.drop_column('pending_disconnect')
        batch_op.drop_column('live_connections')
        batch_op.drop_column('note')

    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_codes_user_id'))

    op.drop_table('recovery_codes')
    with op.batch_alter_table('login_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_challenges_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_challenges_secret_hash'))
        batch_op.drop_index(batch_op.f('ix_login_challenges_expires_at'))

    op.drop_table('login_challenges')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_name'))

    op.drop_table('strategies')
    # ### end Alembic commands ###
