"""accounts lockout api keys device events

Revision ID: e6b3a8d1c5f2
Revises: d5a1c7e9b3f4
Create Date: 2026-09-20 22:03:55.480016
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e6b3a8d1c5f2'
down_revision: Union[str, None] = 'd5a1c7e9b3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_password_reset_tokens_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('saved_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_views_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views')),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_views_user_name')
    )
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_views_user_id'), ['user_id'], unique=False)

    op.create_table('device_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_events_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_events'))
    )
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_device_events_device_created', ['device_id', 'created_at'], unique=False)

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=10), server_default='full', nullable=False))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_uuid', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pending_uuid_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('pending_uuid_ip', sa.String(length=64), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_logins', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_logins')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('pending_uuid_ip')
        batch_op.drop_column('pending_uuid_at')
        batch_op.drop_column('pending_uuid')

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_column('scope')

    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.drop_index('ix_device_events_device_created')
        batch_op.drop_index(batch_op.f('ix_device_events_created_at'))

    op.drop_table('device_events')
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_views_user_id'))

    op.drop_table('saved_views')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
