"""address book entries

Revision ID: f8f7abb28559
Revises: c1a346230d0a
Create Date: 2026-09-18 12:29:32.748543
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8f7abb28559'
down_revision: Union[str, None] = 'c1a346230d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_book_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('rustdesk_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_address_book_entries_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address_book_entries')),
    sa.UniqueConstraint('owner_id', 'rustdesk_id', name='uq_ab_entry_owner_rustdesk_id')
    )
    with op.batch_alter_table('address_book_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_book_entries_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_book_entries_rustdesk_id'), ['rustdesk_id'], unique=False)

    op.create_table('address_book_entry_tags',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['address_book_entries.id'], name=op.f('fk_address_book_entry_tags_entry_id_address_book_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_address_book_entry_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id', name=op.f('pk_address_book_entry_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address_book_entry_tags')
    with op.batch_alter_table('address_book_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_book_entries_rustdesk_id'))
        batch_op.drop_index(batch_op.f('ix_address_book_entries_owner_id'))

    op.drop_table('address_book_entries')
    # ### end Alembic commands ###
