"""Which language the WebUI pages are served in, and the new pages that exist."""

from __future__ import annotations

import re

import pytest


def _lang(response) -> str:
    return re.search(r'<html lang="([^"]+)"', response.text).group(1)


def test_english_is_the_default_and_needs_no_catalog(client):
    page = client.get("/login")
    assert _lang(page) == "en"
    assert "/static/i18n/" not in page.text
    assert 'id="lang-select"' in page.text


@pytest.mark.parametrize(
    ("header", "expected"),
    [
        ("pl", "pl"),
        ("fr-CA,fr;q=0.9,en;q=0.8", "fr"),
        ("de-DE,de;q=0.9", "de"),
        ("es-419", "es"),
        ("ja,zh;q=0.9", "en"),  # nothing we have: English
        ("ja,pl;q=0.5", "pl"),  # the first one we have, in the browser's order
        ("", "en"),
    ],
)
def test_the_browsers_language_is_used_when_there_is_no_choice(client, header, expected):
    page = client.get("/login", headers={"Accept-Language": header})
    assert _lang(page) == expected
    if expected != "en":
        assert f'src="/static/i18n/{expected}.js"' in page.text


def test_the_chosen_language_wins_over_the_browser(client):
    page = client.get("/login", headers={"Accept-Language": "de"}, cookies={"rd_lang": "fr"})
    assert _lang(page) == "fr"
    # Choosing English explicitly is remembered too.
    page = client.get("/login", headers={"Accept-Language": "de"}, cookies={"rd_lang": "en"})
    assert _lang(page) == "en"


@pytest.mark.parametrize("junk", ["xx", "PL", "../../etc/passwd", '"><script>', ""])
def test_a_cookie_that_names_no_language_is_ignored(client, junk):
    page = client.get("/login", cookies={"rd_lang": junk})
    assert _lang(page) == "en"


@pytest.mark.parametrize("lang", ["pl", "fr", "de", "es"])
def test_every_language_file_is_served_as_script_and_translates_the_navigation(client, lang):
    response = client.get(f"/static/i18n/{lang}.js")
    assert response.status_code == 200
    assert "javascript" in response.headers["content-type"]
    assert response.text.startswith("// Generated by scripts/build_i18n.py")
    assert '"Dashboard":' in response.text and '"Log out":' in response.text


def test_the_pages_load_the_translator_before_the_page_scripts(client):
    page = client.get("/devices", cookies={"rd_lang": "pl"}).text
    assert (
        page.index("/static/i18n/pl.js") < page.index("/static/js/i18n.js") < page.index("/static/js/app.js")
    )
    # The catalog is a script file of our own: no inline script (the CSP allows none).
    assert not re.search(r"<script(?![^>]*\bsrc=)[^>]*>", page)


@pytest.mark.parametrize("path", ["/settings", "/connect"])
def test_the_new_pages_are_served(client, path):
    response = client.get(path)
    assert response.status_code == 200
    assert "RustDesk API Server" in response.text
    assert _lang(response) == "en"
