"""Builds the WebUI's language files from the catalog in frontend/i18n.

    python scripts/build_i18n.py           # write src/rustdesk_api/web/static/i18n/<lang>.js
    python scripts/build_i18n.py --check   # only check that they are up to date (exit 1 if not)

Each frontend/i18n/*.txt line is `English || Polish || French || German || Spanish`. Blank lines
and lines starting with `#` are ignored. `{1}`, `{2}`... are values filled in at run time; a
translation may only use ones the English has (it may leave one out). A key starting with `@`
names an element carrying data-i18n-html (the English stays in the template; the translations are
HTML). A key starting with `!` is only for t() in the scripts and is never matched against the
text of a page.

Only the standard library is used, so this runs on any machine that has Python (no Node.js).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "frontend" / "i18n"
OUTPUT = ROOT / "src" / "rustdesk_api" / "web" / "static" / "i18n"
LANGUAGES = ("pl", "fr", "de", "es")
SEPARATOR = " || "
_PLACEHOLDER = re.compile(r"\{(\d+)\}")


class CatalogError(Exception):
    pass


def load() -> dict[str, dict[str, str]]:
    """key -> {language: translation}, checked."""
    entries: dict[str, dict[str, str]] = {}
    problems: list[str] = []
    for path in sorted(SOURCE.glob("*.txt")):
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            where = f"{path.name}:{number}"
            fields = line.split(SEPARATOR)
            if len(fields) != 1 + len(LANGUAGES):
                problems.append(
                    f"{where}: expected {1 + len(LANGUAGES)} fields, found {len(fields)}: {line[:60]}"
                )
                continue
            key, *values = (f.strip() for f in fields)
            translations = dict(zip(LANGUAGES, values, strict=True))
            for lang, text in translations.items():
                if not text:
                    problems.append(f"{where}: empty {lang} translation for {key[:50]!r}")
                elif not set(_PLACEHOLDER.findall(text)) <= set(_PLACEHOLDER.findall(key)):
                    # A translation may leave a value out (a plural "s" the language does not need)
                    # but must not use one the English does not have.
                    problems.append(f"{where}: {lang} uses a placeholder the key {key[:50]!r} does not have")
            if key in entries and entries[key] != translations:
                problems.append(f"{where}: {key[:50]!r} is defined twice with different translations")
            entries[key] = translations
    if problems:
        raise CatalogError("\n".join(problems))
    return entries


def render(entries: dict[str, dict[str, str]], lang: str) -> str:
    body = {key: value[lang] for key, value in sorted(entries.items())}
    # Escape "</" so the file could never end a <script> element early if it were inlined.
    text = json.dumps(body, ensure_ascii=False, indent=0, sort_keys=True).replace("</", "<\\/")
    return (
        f"// Generated by scripts/build_i18n.py from frontend/i18n - do not edit.\nwindow.RD_I18N = {text};\n"
    )


def main(argv: list[str]) -> int:
    check = "--check" in argv
    try:
        entries = load()
    except CatalogError as exc:
        print(exc, file=sys.stderr)
        return 1
    stale = []
    for lang in LANGUAGES:
        target = OUTPUT / f"{lang}.js"
        wanted = render(entries, lang)
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current != wanted:
            stale.append(target.name)
            if not check:
                OUTPUT.mkdir(parents=True, exist_ok=True)
                # newline="" keeps the file byte-for-byte what the test compares against.
                target.write_text(wanted, encoding="utf-8", newline="\n")
    if check and stale:
        print(f"Out of date: {', '.join(stale)}. Run: python scripts/build_i18n.py", file=sys.stderr)
        return 1
    print(f"{len(entries)} entries, {len(LANGUAGES)} languages" + (" (up to date)" if check else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
